# Generated by Django 2.2.1 on 2021-12-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(default='land', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.IntegerField(default=1000000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='images',
            field=models.ImageField(upload_to='pictures/', verbose_name='Property Picture'),
        ),
    ]
